name: Build and Deploy GitHub Pages 

on:
  push:
    branches:
      - web    # or your default branch
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository.
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: web   # your branch to retrieve the code from


      # 2. Set up Python (choose version 3.10 or 3.11 for compatibility with pygbag).
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3. Install dependencies.
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygbag pygame-ce

      # 4. Build the game with pygbag.
      - name: Build Game with pygbag
        run: |
          pygbag --build --git --PYBUILD  3.12 .
        # The build output is usually placed in the build/web folder.
      
      # 5. Deploy to GitHub Pages using peaceiris/actions-gh-pages.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
